name: Push Docker Image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest

    env:
      IMAGE: ts-dashboard
      DOCKER_STORAGE_IP: 220.135.78.200:9041

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: get-package-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."${{ env.DOCKER_STORAGE_IP }}"]
              http = true
              insecure = true

      # - name: Insecure Docker Repository
      #   run: |
      #     sudo truncate -s-2 /etc/docker/daemon.json
      #     echo ", \"insecure-registries\": [\"${{ env.DOCKER_STORAGE_IP }}\"]}" | sudo tee -a /etc/docker/daemon.json
      #     sudo systemctl restart docker

      # - name: Login to private registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.DOCKER_STORAGE_IP }}
      #     username: ${{ secrets.REGISTRY_STORAGE_S3_AUTH_USERNAME }}
      #     password: ${{ secrets.REGISTRY_STORAGE_S3_AUTH_PASSWORD }}

      - name: Build the Docker image And Push
        id: firs-docker-pull
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}:latest
            ${{ env.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}:${{ steps.package-version.outputs.current-version }}
        continue-on-error: true

      - name: Retry again on failure Build the Docker image And Push
        id: second-docker-pull
        if: steps.firs-docker-pull.outcome != 'success'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}:latest
            ${{ env.DOCKER_STORAGE_IP }}/${{ env.IMAGE }}:${{ steps.package-version.outputs.current-version }}

#    - name: Invoke deployment hook
#      uses: distributhor/workflow-webhook@v2
#      env:
#        webhook_url: ${{ secrets.WEBHOOK_URL }}/mkl-api-build-webhook
#        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
#        webhook_auth: ${{ secrets.WEBHOOK_USERNAME }}:${{ secrets.WEBHOOK_PASSWORD }}
